### ISSUE TITLE
undefined local variable or method `e'

### ISSUE THREAD

**Issue by pboling** [wordtreefoundation/archdown#1]
Error occured wile downloading 1808:

```
title: On Caloric
author: W.
year: 1808
source: http://archive.org/details/jstor-30072110
status: OCR ONLY
archive_org_id: jstor-30072110

---
title: Table-Talk (Continued)
author: 
year: 1808
source: http://archive.org/details/jstor-30072106
status: OCR ONLY
archive_org_id: jstor-30072106

---
title: Account of the Late Melancholy Shipwreck at Ballycastle
author: Conolly, L. A.
year: 1808
source: http://archive.org/details/jstor-30072117
status: OCR ONLY
archive_org_id: jstor-30072117

---
title: Meteorological Report
author: 
year: 1808
source: http://archive.org/details/jstor-30072150
status: OCR ONLY
archive_org_id: jstor-30072150

---
title: Lines
author: X.
year: 1808
source: http://archive.org/details/jstor-30072123
status: OCR ONLY
archive_org_id: jstor-30072123
/home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/archdown-0.4.1/lib/archdown/download.rb:24:in `rescue in block (2 levels) in go!': undefined local variable or method `e' for #<Archdown::Download:0x007f230c280290> (NameError)
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/archdown-0.4.1/lib/archdown/download.rb:22:in `block (2 levels) in go!'
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:53:in `block in retriable'
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `each'
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `with_index'
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `retriable'
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/archdown-0.4.1/lib/archdown/download.rb:20:in `block in go!'
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/archdown-0.4.1/lib/archdown/download.rb:19:in `loop'
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/archdown-0.4.1/lib/archdown/download.rb:19:in `go!'
    from /home/pboling/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/archdown-0.4.1/bin/archdown:33:in `<top (required)>'
    from /home/pboling/.rbenv/versions/2.2.1/bin/archdown:23:in `load'
    from /home/pboling/.rbenv/versions/2.2.1/bin/archdown:23:in `<main>'
```

Appears that it is a typo, perhaps a typo in an error handler.  Will investigate.

**Comment by canadaduane** [comment]
Good catch. It looks like it's missing the rocket (rescue => e) which is causing an exception in the exception handler. Not sure what the original exception is, however.
